apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo
data:
  rootPassword: cm9vdA== # root
  password: YWRtaW4= # admin
type: Opaque
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: demo
  labels:
    app: mysql
data:
  username: wp-user
  database: wp-db
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: demo
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: demo
spec:
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database 
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootPassword
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports: 
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /srv/nfs/mydata
          name: mysql-pvc
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  namespace: demo
  name: mysql-svc
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
